version: '3.8'

services:
  springboot-app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: "host.docker.internal"
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "840122"
      MYSQL_DATABASE: "smartiot"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local

# docker-compose up